version: '3.9'
services:
    # Client
    complect-client:
        container_name: complect-client
        hostname: client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: complect-client:1.0
        ports:
            - 80:5000 # Build
            - 81:5001 #Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./client:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev