version: '3.9'
services:
    
    # Client
    complect-client:
        container_name: complect-client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: complect-client:1.0
        ports:
            - ${CLIENT_PORT}:5000
        environment:
            HOST: 0.0.0.0
            VITE_API_URI: ${CLOUD_API_URI}
            VITE_STAGE: 'dev'
        volumes:
            - ./client:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev
