version: '3.9'
services:
    # Front End
    complect-front-end:
        container_name: complect-front-end
        hostname: front
        build:
            context: ./front-end
            dockerfile: Dockerfile
        image: complect-front-end:1.0
        ports:
            - 80:5000 # Build
            - 81:5001 #Dev
        environment:
            HOST: 0.0.0.0
        volumes:
            - ./front-end:/home/app
            - /home/app/node_modules
        working_dir: /home/app
        command: npm run dev