const icons = [
	{ title: "Logo", value: "logo", icon: "logo" },
	{ title: "Brandname", value: "brandname", icon: "brandname" },
	{ title: "List", value: "list-outline", icon: "list-outline" },
	{ title: "Document", value: "document", icon: "document" },
	{ title: "Settings", value: "settings", icon: "settings" },
	{ title: "Close", value: "close", icon: "close" },
	{ title: "Tag", value: "tag", icon: "tag" },
	{ title: "Login", value: "login", icon: "login" },
	{ title: "Bell", value: "bell", icon: "bell" },
	{ title: "Star", value: "star", icon: "star" },
	{ title: "Refresh", value: "refresh", icon: "refresh" },
	{ title: "Briefcase", value: "briefcase", icon: "briefcase" },
	{ title: "Business", value: "business", icon: "business" },
	{ title: "Chevron (Up)", value: "chevron-up", icon: "chevron-up" },
	{ title: "Chevron (Down)", value: "chevron-down", icon: "chevron-down" },
	{ title: "Chevron (Left)", value: "chevron-left", icon: "chevron-left" },
	{ title: "Chevron (Right)", value: "chevron-right", icon: "chevron-right" },
	{ title: "Drop-Up", value: "drop-up", icon: "drop-up" },
	{ title: "Drop-Down", value: "drop-down", icon: "drop-down" },
	{ title: "Sort", value: "sort", icon: "sort" },
	
	{ title: "Info", value: "info", icon: "info" },
	{ title: "Success", value: "success", icon: "success" },
	{ title: "Warning", value: "warning", icon: "warning" },
	{ title: "Error", value: "error", icon: "error" },
	{ title: "Empty", value: "empty-state", icon: "empty-state" },
	{ title: "Mail", value: "mail", icon: "mail" },

	{ title: "Required", value: "required", icon: "required" },
	{ title: "Text", value: "text", icon: "text" },
	{ title: "Email", value: "email", icon: "email" },
	{ title: "Password", value: "password", icon: "password" },
	{ title: "Number", value: "number", icon: "number" },
	{ title: "Url", value: "url", icon: "url" },
	{ title: "Tel", value: "tel", icon: "tel" },
	{ title: "Date", value: "date", icon: "date" },
	{ title: "Time", value: "time", icon: "time" },
	{ title: "Color", value: "color", icon: "color" },
	{ title: "File", value: "file", icon: "file" },
	{ title: "Range", value: "range", icon: "range" },
	{ title: "Search", value: "search", icon: "search" },
	{ title: "Edit", value: "edit", icon: "edit" },
	{ title: "Check", value: "check", icon: "check" },
	{ title: "Circle Plus", value: "circle_plus", icon: "circle_plus" },
]

export { icons }