service: "complect-api"
useDotenv: true

provider:
  name: "aws"
  runtime: "nodejs14.x"
  memorySize: 128
  timeout: 3
  region: "us-east-1"
  stage: ${opt:stage, "dev"}
  lambdaHashingVersion: 20201221
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    disableDefaultEndpoint: true
    cors: true
  environment: 
    NODE_ENV: "dev"
    DB_URI: ${env:DB_URI}
    DB_NAME: ${env:DB_NAME}
    STAGE: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
        - "s3:GetObject"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::<s3-bucket-name>/*"

functions:
  - "${file(endpoints/auth.yml)}"
  - "${file(endpoints/data.yml)}"
  # - "${file(endpoints/download.yml)}"
  # - "${file(endpoints/cron.yml)}"
  - "${file(endpoints/_debug.yml)}"

package:
  patterns:
    - "!.aws/**"
    - "!coverage/**"
    - "!endpoints/**"
    - "!tests/**"
    - "!Dockerfile"
    - "!jest.config.json"
    - "!.eslintrc.json"
    - "!package.json"
    - "!README.md"
    - "!.DS_Store"
    - "!layers/**"
    - "!node_modules/**"

plugins:
  - "serverless-offline"
  - "serverless-iam-roles-per-function"
  - "serverless-prune-plugin"
  - "serverless-domain-manager"

custom:
  serverless-offline:
    httpPort: 6099
    host: 0.0.0.0
  customDomain:
    domainName: "api.complect.dev"
    basePath: ${self:provider.stage}
    stage:  ${self:provider.stage}
    certificateName: "*.complect.dev"
    endpointType: "edge"
    createRoute53Record: true
  prune:
    automatic: true
    number: 3

layers:
  baseLibs:
    path: layers/base
    description: Basic libraries for most endpoints
    compatibleRuntimes:
      - nodejs14.x
  pdfLibs:
    path: layers/pdf
    description: Additional libraries for PDF generator
    compatibleRuntimes:
      - nodejs14.x
  scraperLibs:
    path: layers/scraper
    description: Additional libraries for Scraper
    compatibleRuntimes:
      - nodejs14.x