service: "complect-api"
useDotenv: true
provider:
  name: "aws"
  runtime: "nodejs14.x"
  memorySize: 128
  timeout: 3
  region: "us-east-1"
  profile: "serverless-framework"
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

  stage: ${env:API_STAGE}
  environment: 
    NODE_ENV: "dev"

functions:
  - "${file(endpoints/data.yml)}"

package:
  patterns:
    - "!.aws/**"
    - "!coverage/**"
    - "!endpoints/**"
    - "!tests/**"
    - "!Dockerfile"
    - "!jest.config.json"
    - "!.eslintrc.json"
    - "!package.json"
    - "!README.md"
    - "!.DS_Store"


plugins:
  - "serverless-offline"
  - "serverless-iam-roles-per-function"
  - "serverless-prune-plugin"
  - "serverless-domain-manager"


custom:
  serverless-offline:
    httpPort: 6099
    host: 0.0.0.0
  customDomain:
    domainName: "api2.complect.com"
    basePath: ${self:provider.stage}
    stage:  ${self:provider.stage}
    certificateName: "*.complect.com"
    endpointType: "edge"
    createRoute53Record: true
  prune:
    automatic: true
    number: 3