service: "complect-api"
useDotenv: true

provider:
  name: "aws"
  runtime: "nodejs14.x"
  memorySize: 128
  timeout: 3
  region: "us-east-1"
  stage: ${opt:stage, "dev"}
  profile: ${self:custom.profiles.${sls:stage}}
  lambdaHashingVersion: 20201221
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    disableDefaultEndpoint: true
    cors: true
  environment: 
    NODE_ENV: "dev"
    DB_URI: ${env:DB_URI}
    DB_NAME: ${env:DB_NAME}
    STAGE: ${opt:stage, "dev"}

functions:
  - "${file(endpoints/auth.yml)}"
  - "${file(endpoints/data.yml)}"

package:
  patterns:
    - "!.aws/**"
    - "!coverage/**"
    - "!endpoints/**"
    - "!tests/**"
    - "!Dockerfile"
    - "!jest.config.json"
    - "!.eslintrc.json"
    - "!package.json"
    - "!README.md"
    - "!.DS_Store"


plugins:
  - "serverless-offline"
  - "serverless-iam-roles-per-function"
  - "serverless-prune-plugin"
  - "serverless-domain-manager"

custom:
  profiles:
    dev: devProfile
    prod: prodProfile
  serverless-offline:
    httpPort: 6099
    host: 0.0.0.0
  customDomain:
    domainName: "api.complect.dev"
    basePath: ${self:provider.stage}
    stage:  ${self:provider.stage}
    certificateName: "*.complect.dev"
    endpointType: "edge"
    createRoute53Record: true
  prune:
    automatic: true
    number: 3