name: API Test
on:
  pull_request:
    branches: [ dev, public ]
    paths:
      - "api/**"
defaults:
  run:
    working-directory: api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code (fix)
        run: npm run lint:fix

      - name: Test code
        run: npm run test

      - name: Install Serverless Framework
        run: npm i -g serverless@2.69.1
      
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: Install dependencies for Base Layer
        run: cd layers/base/nodejs && npm i && cd ../../../
      
      - name: Install dependencies for PDF Layer
        run: cd layers/pdf/nodejs && npm i && cd ../../../
      
      - name: Install dependencies for Scraper Layer
        run: cd layers/scraper/nodejs && npm i && cd ../../../

      - name: Deploy Test Lambda functions
        run: sls deploy --stage test
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          SCHEDULE_TIME: 24
      
      - name: Remove Test Lambda functions
        run: sls remove --stage test
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          SCHEDULE_TIME: 24
