# name: API Deploy (Dev)
# on:
#   push:
#     branches: [ dev ]
#     paths:
#       - "api/**"
# defaults:
#   run:
#     working-directory: api
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
      
#       - name: Checkout
#         uses: actions/checkout@v2
      
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#           cache: 'npm'
#           cache-dependency-path: client/package-lock.json

#       # - name: Deploy
#       #   run: sls deploy
#       #   env:
#       #     API_STAGE: dev
#       #     DB_HOST: ${{ secrets.DB_HOST_DEV }}
#       #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     


